version: '3'
services:
  stack-overflow-2:
    build:
      context: .
    working_dir: /home/ctf
    ports:
      - "31337:31337" # exposed:local
    entrypoint: /etc/run_xinetd.sh
    read_only: true
